version : '3.7'

services:
    elastic:
        image: 'shikloshi/elastic-snyk:1.0'
        networks:
            elastic:
                aliases:
                    - "elasticsearch"
        ports:
            - "9200:9200"
        environment:
            - "discovery.type=single-node"
            - "node.name=elasticsearch"
    kibana:
        image: 'docker.elastic.co/kibana/kibana:7.3.1'
        ports:
            - "5601:5601"
        networks:
            - elastic
        depends_on: 
            - elastic
    stats-server:
        build: "./"
        ports:
            - "3001:3001"
        networks:
            - elastic
        depends_on:
            - elastic
        restart: always


networks:
    elastic:
